// lib/commands/task.ts
import { BrewContext, BrewResult, BrewTaskResult } from "./types";

// import { callPrimaryModel } from "../llm/primary"; // later

export async function handleTaskCommand(
  input: string,
  ctx: BrewContext
): Promise<BrewResult> {
  // TEMP: stub logic – replace with real LLM call.
  const title = input.trim() || "Untitled BrewAssist Task";

  const result: BrewTaskResult = {
    kind: "task",
    summary: `Created task for: ${title}`,
    task: {
      title,
      description:
        "Generated by BrewAssist command stub. Replace with LLM-backed description.",
      tags: ["stub", "command"],
      riskLevel: "low",
      estimate: "TBD",
    },
  };

  return result;
}
